# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

insert_node <- function(heap, node) {
    .Call('_DCEM_insert_node', PACKAGE = 'DCEM', heap, node)
}

remove_node <- function(heap, node_key) {
    .Call('_DCEM_remove_node', PACKAGE = 'DCEM', heap, node_key)
}

get_leaves <- function(heap) {
    .Call('_DCEM_get_leaves', PACKAGE = 'DCEM', heap)
}

max_heapify <- function(data, index, N) {
    .Call('_DCEM_max_heapify', PACKAGE = 'DCEM', data, index, N)
}

build_heap <- function(data) {
    .Call('_DCEM_build_heap', PACKAGE = 'DCEM', data)
}

